title: LearnLock
email: mug.n.ai.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn new words directly from your lock screen
baseurl: "/LearnLock"
url: "https://mug-n-ai.github.io"
github_username:  mug-n-ai


# Build settings
theme: minimal-mistakes-jekyll

# Theme-specific settings
minimal_mistakes_skin: "default"

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Custom Dictionaries"
    url: /custom_dictionaries/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

# Sidebar Settings (Optional)
sidebar:
  nav: "main"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives


markdown: kramdown
kramdown:
  input: GFM
  permalink: pretty


